<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<style> 
input[type=text] {
  width: 30%;
  padding: 12px 20px;
  margin: 8px 0;
  box-sizing: border-box;
  border: 2px solid red;
  border-radius: 4px;
  font-family:'Copperplate';
  font-size: medium;
}
p{
    font-family:'Times New Roman', Times, serif;
  font-size: larger;
}
.button {
  background-color: #4CAF50; /* Green */
  border: none;
  color: white;
  padding: 16px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  transition-duration: 0.4s;
  cursor: pointer;
}

.login {
  background-color: white; 
  color: black; 
  border: 2px solid #4CAF50;
}

.login:hover {
  background-color: #4CAF50;
  color: white;
}
.login {padding: 16px 32px;}



</style>

<h2>Login form</h2>

<?php echo $this->tag->form("/login/login"); ?>

    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField("email"); ?>
    </p>
    <p>
        <label for="password">Password</label>
        <?php echo $this->tag->textField("password"); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton(["login",'class' => 'btn btn-success']); ?>
        
    </p>

</form>